package main

import (
	"database/sql"
	"fmt"
	"log"
	"os"

	_ "github.com/lib/pq"
)

type Config struct {
	DSN string
}

func loadConfig() (*Config, error) {
	host := os.Getenv("DB_HOST")
	port := os.Getenv("DB_PORT")
	user := os.Getenv("DB_USER")
	passwd := os.Getenv("DB_PASSWD")
	dbName := os.Getenv("DB_NAME")
	if host == "" {
		host = "postgres-svc"
	}
	if port == "" {
		port = "5432"
	}
	if user == "" || passwd == "" || dbName == "" {
		return nil, fmt.Errorf(
			`missing required environment variables (DB_USER, DB_PASSWD, or DB_NAME)`)
	}
	dsn := fmt.Sprintf(
		"host=%s port=%s user=%s password=%s dbname=%s sslmode=disable",
		host, port, user, passwd, dbName,
	)
	return &Config{DSN: dsn}, nil
}

func openDB() (*sql.DB, error) {
	cfg, err := loadConfig()
	if err != nil {
		return nil, err
	}
	db, err := sql.Open("postgres", cfg.DSN)
	if err != nil {
		return nil, err
	}
	err = db.Ping()
	if err != nil {
		db.Close()
		return nil, err
	}
	return db, nil
}

func createInitialseTable(db *sql.DB) error {
	stmt := `CREATE TABLE IF NOT EXISTS tasks (
        id    INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        title TEXT NOT NULL,
        state SMALLINT NOT NULL CHECK (state IN (0, 1))
    );`
	if _, err := db.Exec(stmt); err != nil {
		return err
	}

	seedStmt := `INSERT INTO tasks (id, title, state) VALUES
        (1, 'Buy groceries', 1),
        (2, 'Finish project documentation', 0),
        (3, 'Schedule dentist appointment', 0),
        (4, 'Pay electricity bill', 1)
    ON CONFLICT (id) DO NOTHING;`

	if _, err := db.Exec(seedStmt); err != nil {
		return err
	}

	// This prevents "duplicate key" errors on your next manual
	// insert. Think of this line as "manually fast-forwarding" the
	// counter to match your data:
	resetSeq := `SELECT setval(pg_get_serial_sequence('tasks', 'id'),
                        COALESCE(MAX(id), 0) + 1, false) FROM tasks;`
	if _, err := db.Exec(resetSeq); err != nil {
		return err
	}

	log.Println("Database initialized and sequences synced.")
	return nil
}
